version: '2.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 4G

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_MESSAGE_MAX_BYTES: 11534336
      KAFKA_REPLICA_FETCH_MAX_BYTES: 11534336
      KAFKA_CREATE_TOPICS: "big-message-test:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "SSL://127.0.0.1:9093,PLAINTEXT://127.0.0.1:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      ZK: "zk"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 4G
    depends_on:
      - "zookeeper"

  kafka_integration_test:
    build:
      context: ../../../
      dockerfile: ./deployments/tikv-cdc/docker/integration-test.Dockerfile
      args:
        - TEST_ON_BRANCH=release-6.5
    depends_on:
      - "zookeeper"
      - "kafka"
    command:
      - bash
      - -c
      - tests/integration_tests/run.sh kafka "${CASE}" & tail -f /dev/null
    network_mode: "service:kafka"
    volumes:
      - /tmp/tikv_cdc_test/:/tmp/tikv_cdc_test
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          memory: 12G
